apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
    app: student
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        -  name: student-cont
           image: 655887417250.dkr.ecr.ap-southeast-1.amazonaws.com/student-service:${student_service_tag}
           ports:
             - containerPort: 8080
           imagePullPolicy: always
        
           resources:
             requests:
               cpu: '100m'
               memory: '64Mi'
             limits:
               cpu: '200m'
               memory: '128Mi'
  